[package]
name = "goodboy"
version = "0.4.0"
edition = "2021"

[workspace]
members = ["goodboy-core"]

[profile.release]
incremental=true
# opt-level = 2


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
goodboy_core = { path = "./goodboy-core" }
rfd = "0.7.0"
eframe = "0.16.0"
env_logger = "0.9.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
smol = "1.2.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.29"
