[package]
name = "sixels_gb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.9"
winit = "0.25.0"
pixels = "0.5.0"
