[package]
name = "sixels_gb"
version = "0.1.0"
edition = "2018"
resolver = "2"

# [lib]
# crate-type = ["cdylib"]

[dependencies]
bitflags = "1.2"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.9"

winit_input_helper = "0.10"
winit = "0.25"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pixels = "0.7.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.25", features = ["web-sys"] }

web-sys = { version = "0.3.55", features = [
    'CanvasRenderingContext2d',
    'Document',
    'Element',
    'HtmlCanvasElement',
    'Window',
    'ImageData',
] }
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"


console_log = "0.2"

# wgpu = { version = "0.11", features = ["webgl"] }
glow = "0.11"
