[package]
name = "goodboy"
version = "0.4.0"
edition = "2021"

[workspace]
members = ["goodboy-core"]

[profile.release]
incremental=true
# opt-level = 2


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
goodboy_core = { path = "./goodboy-core" }
eframe = "0.16.0"

